#lang racket
(define (cont-frac n d k)
  (define (iter i)
    (/ (n 1) (+ (d i)
                (if (< i k)
                    (iter (+ i 1))
                    0))))
  (iter 1))

(define (e k)
  (+ 2 (cont-frac (lambda (i) 1.0)
                  (lambda (i) (if (= (remainder i 3) 2)
                                  (* 2 (/(+ i 1) 3))
                                  1))
     k)))